### ISSUE TITLE
Ulta graphic/high performance mode in some games not available 

### ISSUE THREAD

**Issue by mnkh4ntt** [dm700-devs/OTA#1]
![Screenshot_20230616-113819_Mobile Legends_ Bang Bang](https://github.com/dm700-devs/OTA/assets/101708856/2bbebc36-1605-40f8-9389-a2d0c48a61d7)

Loving the build, 
It had "ultra" option back in miui.
If I remember correctly, you can spoof the device's performance to unlock these options in some roms( even in pe rom?). Somewhere in the gaming dashboard or something like that. Would be cool if it has that 😊

**Comment by rio004** [comment]
PE spoofs the device to pass safetynet, maybe that's why it's not showing. You could always use magisk to spoof your device to get it back.
