### ISSUE TITLE
Update Verification Failed .

### ISSUE THREAD

**Issue by Rudra0Panda** [dm700-devs/OTA#2]
![Screenshot_20231105-115239_Chrome](https://github.com/dm700-devs/OTA/assets/71683445/a5a088e4-b951-4ee1-a00e-11bf83a5c897)

**Comment by Bruhipie** [comment]
This has been an issue, even in the last build. Just flash the build manually. That is, just side load the new build from recovery.

**Comment by rio004** [comment]
Since I switched to new trees manually flashing it is the only option.
I also recommend a clean flash.
