### ISSUE TITLE
Mobile internet and bluetooth issues.

### ISSUE THREAD

**Issue by MistGo** [dm700-devs/OTA#3]
When I upgraded to the new firmware version, the mobile internet stopped working for me, it finds the network, but it doesn't load in different applications (also APN empty). I pulled out and inserted the SIM card, but this problem was not solved.
And bluetooth, at the beginning of the video or music, he can raise the volume to the maximum, but to fix it, you need to press the volume buttons.

Phone: POCO M3 Pro 5G, global version
Bluetooth headphones: Redmi Buds 4 Pro, global version.

**Comment by rio004** [comment]
The new trees recommend you to add your carrier APNs and about your Bluetooth issue could explain it abit better?

**Comment by MistGo** [comment]
After several days of testing, the problem with Bluetooth did not appear.
