### ISSUE TITLE
Google Wallet not working

### ISSUE THREAD

**Issue by nisel11** [dm700-devs/OTA#6]
Google Wallet doesn't work on Pixel Experience, by searching the internet I haven't found anything without using root, hopefully this can be fixed in the update

![Screenshot_20231112-134239_Google.png](https://github.com/dm700-devs/OTA/assets/96194200/3e6304a7-5b32-4f7a-9a5c-1dca442d80a9)

**Comment by rio004** [comment]
This cannot be fixed via updates as it's server side issue.

**Comment by nisel11** [comment]
Looks like this problem is due to the fact that I'm not passing MEETS_DEVICE_INTEGRITY, sorry if I'm wasting your time.

I found this issue on reddit, this may give more information: https://www.reddit.com/r/PixelExperience/comments/17qwz9j/play_integrity/

![Screenshot_20231113-184808_Play Integrity API Checker.png](https://github.com/dm700-devs/OTA/assets/96194200/d2f8933d-f19a-4f0b-943e-b643c4398176)

I’ll also add a screenshot from the xiaomi forum with a discussion of this problem

![Screenshot_20231113-222255_Chrome.png](https://github.com/dm700-devs/OTA/assets/96194200/94911528-7035-4b68-ae9c-a628bf0086b9)

Whoa, response from google support.

![image](https://github.com/dm700-devs/OTA/assets/96194200/e1fccc3b-43a6-48ef-95ac-7f5bf4530df6)
