### ISSUE TITLE
evolution x launcher crashes no app loading also this device isn't play protect certified error kindly solve it

### ISSUE THREAD

**Issue by taiyabansari** [dm700-devs/OTA#7]
I have installed this rom(evolution x 14)on my Redmi note 10t device.It has lot of bugs 
          1.wi-fi not working 
          2. Evolution x launcher crash
          3. Hotspot not working 
          4.Not verified by play protect

**Comment by ProfDrToast** [comment]
Ive got the same Problem on a Redmi Note 10 g5

**Comment by rio004** [comment]
It looks like you dirty flashed to A14, try wiping your data.
And for play store not being verified is something I can't fix currently which is also stated in https://github.com/dm700-devs/OTA/issues/6.

**Comment by taiyabansari** [comment]
After clean flash  everything is working fine except evox launcher and Google play certificate
